openhab: "http://192.168.0.1:8080/"
timeout: 3
devices:

  Kitchen_Outlets:
    type: OUTLET
    name: Outlets
    room: Kitchen
    traits:
      OnOff: Kitchen_Power

  Livingroom_Light:
    type: LIGHT
    name: Light
    room: Living Room
    traits:
      OnOff: Livingroom_Light_Power
      Brightness: Livingroom_Light_Brightness

  Bedroom_WallLamp:
    type: LIGHT
    name: Wall Lamp
    room: Bedroom
    traits:
      OnOff: BR_WallLamp_Power
      Brightness: BR_WallLamp_Brightness
      ColorSetting: BR_WallLamp_ColorTemperature
    attributes:
      colorTemperatureRange:
        temperatureMinK: 2700
        temperatureMaxK: 6500

  Livingroom_RGBLamp:
    type: LIGHT
    name: Wall Lamp
    room: Livingroom
    traits:
      OnOff: LR_WallLamp_Power
      Brightness: LR_WallLamp_Brightness
      ColorSetting: LR_WallLamp_ColorRGB
    attributes:
      colorModel: rgb
